require_relative 'schemas/classes'

require_relative 'schemas/base'
require_relative 'schemas/discriminator'
require_relative 'schemas/openapi'
require_relative 'schemas/paths'
require_relative 'schemas/path_item'
require_relative 'schemas/operation'
require_relative 'schemas/parameter'
require_relative 'schemas/reference'
require_relative 'schemas/request_body'
require_relative 'schemas/response'
require_relative 'schemas/responses'
require_relative 'schemas/components'
require_relative 'schemas/media_type'
require_relative 'schemas/schema'
require_relative 'schemas/header'
